#! /bin/sh -ex
#
# Script used in a separate jenkins job to update the scripts on master

cd $JENKINS_HOME/build_scripts
git remote update
git reset --hard origin/master

if test -z "$CONFIG_DIR"; then
    cd $CONFIG_DIR
    git remote update
    git reset --hard origin/master
fi

if test -z "$WWW_TEMPLATE_DIR"; then
    cd $WWW_TEMPLATE_DIR
    git remote update
    git reset --hard origin/master
fi

